### Upload Photo Request

POST {{BASE_URL}}/api/photos
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-photo.png"
Content-Type: image/png

< resources/test.png
--WebAppBoundary--

### Retrieve the uploaded Photo
GET {{BASE_URL}}/api/photos/{{PHOTO_URL}}

###