### Upload Photo Request

POST {{BASE_URL}}/api/photos
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-photo.jpg"
Content-Type: image/jpeg

< resources/test.jpeg
--WebAppBoundary--

### Retrieve the uploaded photo
GET {{BASE_URL}}/api/photos/{{UPLOADED_PHOTO_URL}}