### Create Restaurant
POST {{BASE_URL}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "name": "Quick Bites Cafe",
  "cuisineType": "Indian",
  "contactInformation": "info@quickbites.com",
  "address": {
    "streetNumber": "456",
    "streetName": "MG Road",
    "city": "Delhi",
    "state": "Delhi NCR",
    "postalCode": "100001",
    "country": "India"
  },
  "operatingHours": {
    "monday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "tuesday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "wednesday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "thursday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "friday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "saturday": {
      "openTime": "10:00",
      "closeTime": "16:00"
    },
    "sunday": {
      "openTime": "10:00",
      "closeTime": "16:00"
    }
  },
  "photoIds": ["0cbb89e2-f786-47fb-88e1-3ebd60b530e2.jpg"]
}

### Retrieve all the Restaurants
GET {{BASE_URL}}/api/restaurants

### Retrieve Restaurant by ID
GET {{BASE_URL}}/api/restaurants/{{RESTAURANT_ID}}

### Update Restaurant
PUT {{BASE_URL}}/api/restaurants/{{RESTAURANT_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "name": "Dominos",
  "cuisineType": "Indian",
  "contactInformation": "info@dominos.com",
  "address": {
    "streetNumber": "456",
    "streetName": "MG Road",
    "city": "Delhi",
    "state": "Delhi NCR",
    "postalCode": "100001",
    "country": "India"
  },
  "operatingHours": {
    "monday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "tuesday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "wednesday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "thursday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "friday": {
      "openTime": "09:00",
      "closeTime": "17:00"
    },
    "saturday": {
      "openTime": "10:00",
      "closeTime": "16:00"
    },
    "sunday": {
      "openTime": "10:00",
      "closeTime": "16:00"
    }
  },
  "photoIds": ["0cbb89e2-f786-47fb-88e1-3ebd60b530e2.jpg"]
}

### Delete Restaurant by ID
DELETE {{BASE_URL}}/api/restaurants/{{RESTAURANT_ID}}
Authorization: Bearer {{JWT_TOKEN}}