### Create Review
POST {{BASE_URL}}/api/restaurants/{{RESTAURANT_ID}}/reviews
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "rating": 3,
  "content": "Average experience.",
  "photoIds": ["{{PHOTO_URL}}"]
}